-- 本番用のサンプルデータ（実際の会議を模したデータ）
-- Supabase SQLエディタで実行してください

INSERT INTO calendar_events (
  event_id,
  summary,
  description,
  start_time,
  end_time,
  location,
  meeting_url,
  organizer_email,
  company_name,
  attendees,
  external_attendees,
  has_external_attendees,
  external_count,
  duration_minutes,
  is_important,
  status,
  proposal_status,
  company_urls,
  synced_at
) VALUES
-- 今日の会議
(
  gen_random_uuid(),
  'DX推進プロジェクトキックオフ - 株式会社テクノロジー',
  'デジタルトランスフォーメーション推進に関する初回打ち合わせ。現状の課題ヒアリングと今後の進め方について協議。',
  NOW() + INTERVAL '2 hours',
  NOW() + INTERVAL '3 hours',
  '東京オフィス 会議室A',
  'https://meet.google.com/abc-defg-hij',
  'yannsunn1116@gmail.com',
  '株式会社テクノロジー',
  ARRAY['yannsunn1116@gmail.com', 'tanaka@technology.co.jp', 'suzuki@technology.co.jp'],
  ARRAY['tanaka@technology.co.jp', 'suzuki@technology.co.jp'],
  true,
  2,
  60,
  true,
  'confirmed',
  'pending',
  ARRAY['https://www.technology.co.jp'],
  NOW()
),
-- 明日の会議
(
  gen_random_uuid(),
  'AI導入相談 - サンプル工業株式会社',
  'AIを活用した品質管理システムの導入に関する相談。画像認識技術を使った不良品検出システムについて。',
  NOW() + INTERVAL '1 day' + INTERVAL '10 hours',
  NOW() + INTERVAL '1 day' + INTERVAL '11 hours 30 minutes',
  'オンライン',
  'https://meet.google.com/xyz-abcd-efg',
  'yannsunn1116@gmail.com',
  'サンプル工業株式会社',
  ARRAY['yannsunn1116@gmail.com', 'yamada@sample-kogyo.jp'],
  ARRAY['yamada@sample-kogyo.jp'],
  true,
  1,
  90,
  true,
  'confirmed',
  'pending',
  ARRAY['https://www.sample-kogyo.jp'],
  NOW()
),
-- 2日後の会議
(
  gen_random_uuid(),
  'クラウド移行提案 - ABC商事株式会社',
  'オンプレミスシステムからクラウドへの移行計画。AWSまたはAzureの選定と移行スケジュールについて。',
  NOW() + INTERVAL '2 days' + INTERVAL '14 hours',
  NOW() + INTERVAL '2 days' + INTERVAL '15 hours 30 minutes',
  '品川オフィス',
  'https://teams.microsoft.com/meet/123456',
  'yannsunn1116@gmail.com',
  'ABC商事株式会社',
  ARRAY['yannsunn1116@gmail.com', 'it-team@abc-shoji.com', 'manager@abc-shoji.com'],
  ARRAY['it-team@abc-shoji.com', 'manager@abc-shoji.com'],
  true,
  2,
  90,
  true,
  'confirmed',
  'pending',
  NULL,
  NOW()
),
-- 3日後の会議
(
  gen_random_uuid(),
  'セキュリティ対策相談 - XYZ製造',
  'サイバーセキュリティ強化の提案。ゼロトラストアーキテクチャとEDR導入について。',
  NOW() + INTERVAL '3 days' + INTERVAL '13 hours',
  NOW() + INTERVAL '3 days' + INTERVAL '14 hours',
  'オンライン',
  'https://zoom.us/j/123456789',
  'yannsunn1116@gmail.com',
  'XYZ製造株式会社',
  ARRAY['yannsunn1116@gmail.com', 'security@xyz-mfg.jp'],
  ARRAY['security@xyz-mfg.jp'],
  true,
  1,
  60,
  true,
  'confirmed',
  'pending',
  ARRAY['https://www.xyz-manufacturing.jp'],
  NOW()
),
-- 4日後の会議
(
  gen_random_uuid(),
  'RPA導入検討会 - デジタル商会',
  'RPAツールによる業務自動化の検討。経理業務と在庫管理業務の自動化について。',
  NOW() + INTERVAL '4 days' + INTERVAL '11 hours',
  NOW() + INTERVAL '4 days' + INTERVAL '12 hours',
  '会議室B',
  NULL,
  'yannsunn1116@gmail.com',
  '株式会社デジタル商会',
  ARRAY['yannsunn1116@gmail.com', 'rpa-team@digital.co.jp', 'cfo@digital.co.jp'],
  ARRAY['rpa-team@digital.co.jp', 'cfo@digital.co.jp'],
  true,
  2,
  60,
  true,
  'confirmed',
  'pending',
  NULL,
  NOW()
),
-- 5日後の会議
(
  gen_random_uuid(),
  'ECサイトリニューアル相談 - オンラインストア社',
  'ECサイトのリニューアルとマーケティング自動化ツールの導入について。',
  NOW() + INTERVAL '5 days' + INTERVAL '15 hours',
  NOW() + INTERVAL '5 days' + INTERVAL '16 hours 30 minutes',
  'オンライン',
  'https://meet.google.com/mno-pqrs-tuv',
  'yannsunn1116@gmail.com',
  'オンラインストア株式会社',
  ARRAY['yannsunn1116@gmail.com', 'marketing@online-store.jp', 'dev@online-store.jp'],
  ARRAY['marketing@online-store.jp', 'dev@online-store.jp'],
  true,
  2,
  90,
  true,
  'confirmed',
  'pending',
  ARRAY['https://www.online-store.jp'],
  NOW()
),
-- 6日後の会議
(
  gen_random_uuid(),
  'IoTシステム導入提案 - スマート製造',
  'IoTセンサーを活用した製造ラインの可視化と予知保全システムについて。',
  NOW() + INTERVAL '6 days' + INTERVAL '9 hours',
  NOW() + INTERVAL '6 days' + INTERVAL '10 hours 30 minutes',
  '横浜工場',
  'https://meet.google.com/wxy-zabc-def',
  'yannsunn1116@gmail.com',
  'スマート製造株式会社',
  ARRAY['yannsunn1116@gmail.com', 'factory@smart-mfg.co.jp', 'engineer@smart-mfg.co.jp'],
  ARRAY['factory@smart-mfg.co.jp', 'engineer@smart-mfg.co.jp'],
  true,
  2,
  90,
  true,
  'confirmed',
  'pending',
  NULL,
  NOW()
);